import type { Metadata } from "next";
import {
    Anton,
    Audiowide,
    Bebas_Neue,
    Berkshire_Swash,
    Inter,
    Open_Sans,
    Orbitron,
    Oxanium, Roboto,
    Teko
} from "next/font/google";
import "./globals.css";

const timerFont = Anton({
    weight: ['400'],
    subsets: ['latin'],
    display: 'swap', // optional, helps with layout shift
    variable: '--font-timer', // Define the CSS variable name
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${timerFont.variable} antialiased scroll-smooth`}
      >
        {children}
      </body>
    </html>
  );
}
